extends SceneTree
func _initialize() -> void:call_deferred("run")
func run() -> void:
	var state:=FarmState.new_farm("survival");assert(state.claim(Vector2(4,-2)).is_empty())
	assert(FarmResidents.valid(state.residents) and FarmResidents.influence(state)==0)
	var before:=state.serialize();assert(not FarmResidents.act(state,"rosa","accept").is_empty() and state.serialize()==before)
	assert(FarmResidents.act(state,"rosa","meet").is_empty());assert(FarmResidents.act(state,"bento","meet").is_empty())
	before=state.serialize();assert(not FarmResidents.act(state,"bento","accept").is_empty() and state.serialize()==before)
	assert(FarmResidents.act(state,"rosa","accept").is_empty());before=state.serialize()
	assert(not FarmResidents.act(state,"rosa","accept").is_empty() and state.serialize()==before)
	state.inventory.carrot=100;before=state.serialize()
	assert(not FarmResidents.act(state,"rosa","deliver").is_empty() and state.serialize()==before,"Stock cannot bypass truck cargo")
	assert(FarmPickupCargo.transfer(state,"carrot",10,true).is_empty());state.pickup.cargo.egg=3
	var cash:=state.money;var payment:=FarmResidents.reward(state,"rosa")
	assert(FarmResidents.act(state,"rosa","deliver").is_empty())
	assert(state.money==cash+payment and state.pickup.cargo.carrot==2 and state.pickup.cargo.egg==3 and state.inventory.carrot==90)
	assert(FarmResidents.influence(state)==5 and state.residents.rosa.done==1)
	before=state.serialize();assert(not FarmResidents.act(state,"rosa","deliver").is_empty() and state.serialize()==before)
	assert(not FarmResidents.act(state,"rosa","accept").is_empty() and state.serialize()==before)
	state.elapsed=state.residents.rosa.ready_at;assert(FarmResidents.act(state,"rosa","accept").is_empty())
	assert(FarmResidents.order(state,"rosa")=={"carrot":12,"corn":8})
	state.pickup.cargo={"carrot":12};before=state.serialize()
	assert(not FarmResidents.act(state,"rosa","deliver").is_empty() and state.serialize()==before)
	state.pickup.cargo={"carrot":12,"corn":8};assert(FarmResidents.act(state,"rosa","deliver").is_empty())
	assert(FarmResidents.influence(state)==10 and FarmResidents.act(state,"bento","accept").is_empty())
	assert(FarmResidents.act(state,"lia","meet").is_empty())
	before=state.serialize();assert(not FarmResidents.act(state,"lia","accept").is_empty() and state.serialize()==before)
	for i in range(3):
		if not state.residents.bento.active:
			state.elapsed=state.residents.bento.ready_at;assert(FarmResidents.act(state,"bento","accept").is_empty())
		state.pickup.cargo=FarmResidents.order(state,"bento").duplicate()
		assert(FarmPickupCargo.valid(state.pickup.cargo) and FarmResidents.act(state,"bento","deliver").is_empty())
	assert(FarmResidents.influence(state)==25 and FarmResidents.act(state,"lia","accept").is_empty())
	assert(FarmResidents.trust(state,"bento")=="Amigo da casa")
	var restored:=FarmState.new();assert(restored.restore(JSON.parse_string(JSON.stringify(state.serialize()))))
	assert(restored.residents==state.residents and is_equal_approx(restored.pickup.angle,state.pickup.angle) and restored.pickup.cargo==state.pickup.cargo)
	before=restored.serialize()
	for broken in [null,{}, {"known":false,"met":true,"done":0,"active":false,"ready_at":0}, {"known":true,"met":true,"done":-1,"active":false,"ready_at":0}, {"known":true,"met":true,"done":1.5,"active":false,"ready_at":0}, {"known":true,"met":true,"done":0,"active":false,"ready_at":INF}]:
		var data:=state.serialize();data.residents.rosa=broken
		assert(not restored.restore(data) and restored.serialize()==before,"Invalid progress must reject atomically")
	var old:=state.serialize();old.version=22;old.erase("residents")
	assert(restored.restore(old) and restored.residents==FarmResidents.fresh() and restored.pickup==state.pickup)
	var sandbox:=FarmState.new_farm("sandbox");sandbox.claim(Vector2(4,-2))
	assert(FarmResidents.act(sandbox,"rosa","meet").is_empty() and FarmResidents.act(sandbox,"rosa","accept").is_empty())
	assert(not FarmResidents.act(sandbox,"rosa","deliver").is_empty())
	assert(FarmPickupCargo.transfer(sandbox,"carrot",8,true).is_empty());assert(FarmResidents.act(sandbox,"rosa","deliver").is_empty())
	assert(sandbox.inventory.carrot==0 and FarmResidents.influence(sandbox)==5 and sandbox.pickup.cargo.is_empty())
	print("RESIDENTS_OK: cargo-only atomic payments, leftovers, influence unlock, evolving orders, cooldown, no double pay, saves, migration and sandbox")
	quit()
