extends SceneTree

var checks := 0
var failures := 0

func check(condition: bool, message: String) -> void:
	checks+=1
	if not condition:
		failures+=1
		push_error("FAILED: "+message)

func _initialize() -> void:
	var farm:=FarmState.new()
	check(not farm.claim(Vector2(-30,0)).is_empty(),"Reject river/road claims")
	check(farm.money==1600 and not farm.claimed,"Invalid claim is atomic")
	check(farm.claim(Vector2(4,0)).is_empty(),"Claim valid terrain")
	check(farm.money==1200,"Claim charges exactly once")
	farm.claim(Vector2(6,2))
	check(farm.money==1200,"Cannot buy starter land twice")
	check(farm.place("plot",Vector2(4,0),0,"carrot").is_empty(),"Build and seed plot")
	check(not farm.place("barn",Vector2(4,0),0).is_empty(),"Reject overlapping construction")
	check(farm.items.size()==1 and farm.money==1180,"Rejected build changes nothing")
	check(not farm.place("plot",Vector2(30,0),0).is_empty(),"Reject out-of-property build")
	farm.tick(90)
	check(farm.items[0].growth==0,"Unwatered plants do not grow")
	farm.tend(0)
	farm.tick(32)
	check(farm.items[0].growth==1,"Watered carrot matures")
	farm.tend(0)
	check(farm.inventory.carrot==3 and farm.harvests==1,"Harvest produces exact yield")
	farm.tend(0)
	check(farm.inventory.carrot==3 and farm.money==1176,"Second interaction replants instead of duplicating harvest")
	check(farm.sale_value()==36,"Crop valuation")
	check(farm.sell_all()==36 and farm.money==1212,"Sale income")
	check(farm.sell_all()==0 and farm.money==1212,"Empty sale is idempotent")
	check(farm.place("coop",Vector2(10,-6),0).is_empty(),"Coop construction")
	farm.tick(91)
	check(farm.inventory.egg==4,"Coop handles multiple production cycles")
	check(not farm.deliver_contract(),"Contract requires stock")
	farm.inventory.carrot=6
	check(farm.deliver_contract(),"Contract consumes carrots and pays")
	var balance:=farm.money
	farm.inventory.carrot=6
	check(not farm.deliver_contract() and farm.money==balance,"Contract cannot pay twice")
	check(farm.expand().is_empty() and farm.land_size==32,"Paid expansion")
	check(not farm.expand().is_empty() and farm.land_size==32,"Insufficient money expansion changes nothing")
	farm.items[1].paint=2
	farm.farm_name="Sítio do João"
	var data:Variant=JSON.parse_string(JSON.stringify(farm.serialize()))
	var restored:=FarmState.new()
	check(restored.restore(data),"JSON roundtrip must restore")
	check(restored.money==farm.money and restored.inventory==farm.inventory,"Money and stock persist")
	check(restored.items.size()==2 and restored.items[1].paint==2,"Construction and paint persist")
	check(restored.farm_name=="Sítio do João","Unicode farm name persists")
	data.items[0].crop="invalid"
	check(not restored.restore(data),"Reject malformed crop data")
	check(restored.money==farm.money and restored.items[0].crop=="carrot","Invalid save is atomic")
	check(not restored.restore(null),"Reject unreadable JSON")
	data=farm.serialize()
	data.items.append(data.items[0].duplicate())
	check(not restored.restore(data),"Reject overlapping saved structures")
	farm.money=0
	check(not farm.place("fence",Vector2(0,6),0).is_empty(),"Prevent negative balance")
	farm.items[0].growth=0.42
	farm.items[0].watered=true
	var original:Dictionary=farm.items[0].duplicate(true)
	check(farm.can_move(0,Vector2(original.x,original.z),0).is_empty(),"Moving ignores its own occupied footprint")
	check(not farm.move_item(0,Vector2(10,-6),0).is_empty(),"Moving rejects occupied destination")
	check(farm.items[0]==original,"Rejected move preserves complete record")
	check(not farm.move_item(0,Vector2(80,0),0).is_empty(),"Moving rejects property boundary")
	check(not farm.move_item(-1,Vector2.ZERO,0).is_empty(),"Moving rejects invalid selection")
	check(farm.move_item(0,Vector2(2,4),1).is_empty(),"Moving and rotating works without money")
	check(farm.items[0].x==2 and farm.items[0].z==4 and farm.items[0].turn==1,"Move commits the destination")
	check(farm.items[0].growth==0.42 and farm.items[0].watered and farm.items[0].crop==original.crop,"Moving preserves crop progress")
	check(farm.money==0 and farm.items.size()==2,"Moving neither charges nor duplicates objects")
	var road_farm:=FarmState.new()
	road_farm.claim(Vector2(-12,0))
	road_farm.expand()
	road_farm.place("sign",Vector2(-18,0),0)
	check(not road_farm.move_item(0,Vector2(-26,0),0).is_empty(),"Moving respects public roads")
	var journey:=FarmState.new()
	check(journey.journey_step()==0,"Tutorial begins at land choice")
	journey.claim(Vector2(4,0))
	check(journey.journey_step()==1,"Tutorial advances after land purchase")
	for at in [Vector2(2,0),Vector2(4,0),Vector2(6,0)]: journey.place("plot",at,0)
	check(journey.journey_step()==2,"Three plots complete planting objective")
	journey.tend(0)
	journey.tend(0)
	check(journey.journey_step()==2,"Repeated watering cannot complete distinct-plot objective")
	journey.tend(1)
	journey.tend(2)
	check(journey.journey_step()==3,"Three watered plots complete care objective")
	var legacy:=journey.serialize()
	legacy.version=1
	legacy.erase("milestones")
	legacy.erase("reserve")
	legacy.erase("watering_upgrade")
	var migrated:=FarmState.new()
	check(migrated.restore(JSON.parse_string(JSON.stringify(legacy))),"Version 0.1 save remains readable")
	check(migrated.journey_step()==3 and migrated.money==journey.money,"Legacy migration derives objectives without changing economy")
	journey.tick(32)
	journey.tend(0)
	check(journey.journey_step()==4,"First harvest objective")
	journey.sell_all()
	check(journey.journey_step()==5,"First sale objective")
	journey.tend(1)
	journey.tend(2)
	journey.deliver_contract()
	check(journey.journey_step()==6,"Contract objective")
	journey.place("coop",Vector2(10,-6),0)
	check(journey.journey_step()==7,"Animal objective")
	journey.expand()
	check(journey.journey_step()==8,"Expansion finishes introductory chapter")
	journey.items.clear()
	journey.refresh_journey()
	check(journey.journey_step()==8,"Removing buildings does not undo completed objectives")
	check(migrated.restore(JSON.parse_string(JSON.stringify(journey.serialize()))) and migrated.journey_step()==8,"Completed objectives survive disk serialization")
	var invalid:=journey.serialize()
	invalid.milestones={"land":"yes"}
	check(not migrated.restore(invalid),"Malformed milestones are rejected atomically")
	print("SIMULATION: %d checks, %d failures"%[checks,failures])
	quit(0 if failures==0 else 1)
