"""Editable Blender ready/aim/reload action and two palm markers for the P-8.
Coordinates exported in Godot model axes (+Z forward, +Y up).
"""
import bpy,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
scene=bpy.context.scene;scene.render.fps=30;scene.frame_end=60
# Pose controls use game axes explicitly, so values match the runtime rig.
controls={
 'weapon':[(.10,1.20,.46),(.10,1.88,.40),(.12,1.38,.40)],
 'rotation':[(-.45,0,0),(0,0,0),(-.55,0,-.25)],
 'UpperArm.R':[(-.75,0,-.12),(-1.3,0,-.12),(-.70,0,-.2)],
 'UpperArm.L':[(-.65,0,.30),(-1.15,0,.35),(-.6,0,.4)],
 'Forearm.R':[(-.75,0,0),(-.45,0,0),(-.9,0,0)],
 'Forearm.L':[(-1.0,0,0),(-.9,0,0),(-1.1,0,0)],
}
objects={}
for key,values in controls.items():
 ob=bpy.data.objects.new(key,None);scene.collection.objects.link(ob)
 ob.empty_display_type='ARROWS';ob.empty_display_size=.2
 for frame,value in zip([0,30,60],values):
  ob.location=value;ob.keyframe_insert('location',frame=frame)
 objects[key]=ob
for key,p in {'grip_right':(.038,.065,-.044),'grip_left':(-.078,.065,-.01)}.items():
 ob=bpy.data.objects.new(key,None);scene.collection.objects.link(ob);ob.location=p;ob.empty_display_type='SPHERE';ob.empty_display_size=.035
out={}
for key,ob in objects.items():
 out[key]=[]
 for f in range(61):
  scene.frame_set(f);out[key].append([round(v,6) for v in ob.location])
scene.frame_set(30)
(ROOT/'assets/animations').mkdir(exist_ok=True)
(ROOT/'assets/animations/pistol_pose.gd').write_text('extends RefCounted\n# Generated by Blender; ready frame0, aim30, reload60.\nconst DATA = '+json.dumps(out,separators=(',',':'))+'\n',encoding='utf8')
bpy.ops.wm.save_as_mainfile(filepath=str(ROOT/'art/source/pistol_pose.blend'))
print('PISTOL_POSE_BLENDER_OK')

